// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthy": {
            "get": {
                "description": "Check if the current API is alive",
                "summary": "Healthy Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/housing": {
            "get": {
                "description": "Search all housing",
                "produces": [
                    "application/json"
                ],
                "summary": "Get all housing",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new housing with given data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Insert a housing",
                "parameters": [
                    {
                        "description": "Housing data",
                        "name": "housing",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Housing"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/housing/status": {
            "get": {
                "description": "Search all housing statuses",
                "produces": [
                    "application/json"
                ],
                "summary": "Get all housing statuses",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new housing status with given data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Insert a housing status",
                "parameters": [
                    {
                        "description": "Housing status data",
                        "name": "status",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Status"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/housing/type": {
            "get": {
                "description": "Search all housing types",
                "produces": [
                    "application/json"
                ],
                "summary": "Get all housing types",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new housing type with given data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Insert a housing type",
                "parameters": [
                    {
                        "description": "Housing type data",
                        "name": "type",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.HousingType"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/housing/{housing_type_id}": {
            "get": {
                "description": "Search all housing of a given type",
                "produces": [
                    "application/json"
                ],
                "summary": "Get all housing by type",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Housing type ID",
                        "name": "housing_type_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Housing": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string",
                    "example": "Lille"
                },
                "country": {
                    "type": "string",
                    "example": "FR"
                },
                "has_electricity": {
                    "type": "boolean",
                    "example": true
                },
                "has_gas": {
                    "type": "boolean",
                    "example": false
                },
                "is_furnished": {
                    "type": "boolean",
                    "example": false
                },
                "last_tenant_id": {
                    "type": "string",
                    "example": "e185deb2-91d5-4ab7-87b3-daaffac00e3d"
                },
                "owner_id": {
                    "type": "string",
                    "example": "e185deb2-91d5-4ab7-87b3-daaffac00e3d"
                },
                "rent_price": {
                    "type": "number",
                    "example": 60.95
                },
                "rental_charges": {
                    "type": "number",
                    "example": 60.9
                },
                "state": {
                    "type": "string",
                    "example": "Haut-de-France"
                },
                "status_id": {
                    "type": "string",
                    "example": "e185deb2-91d5-4ab7-87b3-daaffac00e3d"
                },
                "street": {
                    "type": "string",
                    "example": "78 Rue Solférino"
                },
                "surface_area": {
                    "type": "number",
                    "example": 15.5
                },
                "type_id": {
                    "type": "string",
                    "example": "e185deb2-91d5-4ab7-87b3-daaffac00e3d"
                },
                "zip": {
                    "type": "string",
                    "example": "59000"
                }
            }
        },
        "models.HousingType": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "garage"
                }
            }
        },
        "models.Status": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "sold"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.1.0",
	Host:        "",
	BasePath:    "/api/v1",
	Schemes:     []string{},
	Title:       "Housing API",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
